### ISSUE TITLE
linkhandler ignores ATagParams

### ISSUE THREAD

**Issue by marteb** [Intera/typo3-extension-linkhandler#10]
When using linkhandler for links which are defined in TypoScript like this:

````
link {
	field = header
	typolink {
		parameter.field = header_link
		ATagParams = class="arrow-link"
	}
}
````

the ATagParams will be ignored instead of being succeeded.

**Comment by astehlik** [comment]
Hi, thank you for your report.

To understand this problem you need to understand, how the linkhandler works:

The typolink configuration provided by you is **not** the configuration ```linkhandler``` uses. Within the typolink call from you configuration a hook is triggered which again calls a typolink for generating the record link. The configuration for this link is made within ```plugin.tx_linkhandler.my_link_conf.typolink``` and depends on the linked record type.

By default, the linkhandler does not know anything about the typolink configuration where it is called (see https://github.com/Intera/typo3-extension-linkhandler#pass-on-parent-typolink-configuration).

There is an experimental feature though, which allows the passing of the parent typolink configuration. Please try this:

```
plugin.tx_linkhandler.tx_news_news {
    overrideParentTypolinkConfiguration = 1
    typolink.parameter.field = __UNSET
}
```

Of course you need to replace ```tx_news_news``` with the name of your affected configuration(s).

I hope this helps. Please let me know if you have further questions or problems :)

Cheers,
Alex

**Comment by astehlik** [comment]
One additional remark:

Please note, that editors still can override the configured class by passing it in the ```header_link``` field. E.g. if the value of your ```header_link``` field looks like this:

```
record:tx_news_news:tx_news_domain_model_news:1 _blank myclass
```

The configured ```arrow-link``` class will be overwritten with ```myclass```.

**Comment by marteb** [comment]
Ok, thank you. This works.

My configuration now looks like this:

```
plugin.tx_linkhandler {

	tx_news_news {
		overrideParentTypolinkConfiguration = 1
		typolink {
			parameter = {$site.pid.news}
			parameter.field = __UNSET
			additionalParams = &tx_news_pi1[news]={field:uid}&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail
			additionalParams.insertData = 1
			useCacheHash = 1
		}
	}
}
```

and for a custom content element for links like already written above:

```
link {
    field = header
    typolink {
        parameter.field = header_link
        ATagParams = class="arrow-link"
    }
}
```

**Comment by astehlik** [comment]
I'm glad that I could help :)
