### ISSUE TITLE
pageTreeMountPoints not working

### ISSUE THREAD

**Issue by liayn** [Intera/typo3-extension-linkhandler#11]
Classes/Browser/PageTree.php never evaluates the assigned page uid

**Comment by astehlik** [comment]
Well, it is actually evaluated within [Classes/Browser/TabHandler.php](https://github.com/Intera/typo3-extension-linkhandler/blob/TYPO3_6-2/Classes/Browser/TabHandler.php#L163).

Did you test it?

Adding this to the TSconfig works for me:

```
plugin.tx_linkhandler.tx_news_news {
	pageTreeMountPoints {
		1 = 56
	}
}
```

**Comment by liayn** [comment]
Thanks for checking. I've to re-evaluate this. Is was in a damn big hurry and struggled with a lot of linkhandler extensions and none of them worked. 6.2.12
In this case, I realized that I possibly had the wrong branch in my checkout.

Forget about this one for the time being. I'll test again and report back.

Thanks!
