### ISSUE TITLE
RTE Tab Dialog inserts table name twice

### ISSUE THREAD

**Issue by Mtillmann** [Intera/typo3-extension-linkhandler#12]
`record:table:table:NNN` is inserted instead of `record:table:NNN`.

Apparently this line in RecordListRte.php causes the problem:

`$recordLink = implode(':', array('record', $this->browseLinksObj->act, $table, $row['uid']));`

Is this desired behaviour or an bug? I have patched in my local copy to only use 3 array values instead of 4 including `$this->browseLinksObj->act`

**Comment by liayn** [comment]
Checkout the readme... this a feature of this fork!

https://github.com/Intera/typo3-extension-linkhandler/blob/TYPO3_6-2/README.md#multiple-configurations-for-the-same-table

**Comment by Mtillmann** [comment]
I am using the included default config so i expect the links to look like this `record:tx_news_news:tx_news_domain_model_news:11278`. They are still being generated like this
`record:tx_news_domain_model_news:tx_news_domain_model_news:11278` and fail in the frontend

**Comment by astehlik** [comment]
Thanks for taking your time to report this bug.

First of all: in this version of linkhandler it is intended behavior, that the link parts consist of 4 parts (as Markus already pointed out). This allows linkhandler to link to the same table in different context (e.g. to content elements with different content types).

I have no idea though, why the second part in your links is again the table name. Can you please share some information:

* What TYPO3 version are you using?
* Are you using the TYPO3_6-2 branch of this repository?
* How does your linkhandler configuration look like? You can use the info module in TYPO3 to check how the final configuration in the Page TSconfig in ```mod.tx_linkhandler``` looks like.

I hope we can figure this out.

Cheers,
Alex

**Comment by Mtillmann** [comment]
Guys, thanks for your time and support. The issue has been resolved internally. If I stumble across it again, i will try to get a better description of the problem!
