### ISSUE TITLE
Update to make compatible with TYPO3 7.x

### ISSUE THREAD

**Issue by farconada** [Intera/typo3-extension-linkhandler#13]

**Comment by astehlik** [comment]
As far as I know there are plans to implement a generic record linker directly in the core.

This is why I won't put any effort in this unless it won't be available for the 7LTS release.

**Comment by SventB** [comment]
7.6 LTS is available now, it seems there is no generic record linker in the core :(

There is just a new LinkBrowser API (see https://wiki.typo3.org/TYPO3.CMS/Releases/7.6/Feature#Feature:_.2366369_-_Added_LinkBrowser_APIs), but someone has to write a linkhandler for records. Perhaps I will do that if I have time for that in some weeks.

**Comment by liayn** [comment]
@SventB Go back to the roots ;-) https://github.com/cobwebch/linkhandler/

**Comment by SventB** [comment]
@liayn Thank you for the hint, it seems this fork is compatible with 7 LTS, even if the documentation says it's compatible up to version 7.4.
BTW, the "root" still is http://typo3.org/extensions/repository/view/linkhandler, last update in 2009 ;)

**Comment by liayn** [comment]
"true that is" ;-)

**Comment by astehlik** [comment]
I'm currently trying to merge the features of this patch https://review.typo3.org/#/c/43866/ into the Extension. But it will take some time :(

**Comment by liayn** [comment]
@astehlik Please do not start another fork of the ext here. Please join forces and get one single extension to the desired state. Talk to Francois directly.
Once we have "the perfect" ext ready for 7/8, we can then finally merge it into the Core.

**Comment by astehlik** [comment]
OK, sounds like a plan, thanks for the pointer :)

I will add a link to the README to https://github.com/cobwebch/linkhandler/
