### ISSUE TITLE
Linkhandler in non-RTE context doesn't work on using paginating or search

### ISSUE THREAD

**Issue by lorenzulrich** [Intera/typo3-extension-linkhandler#3]
If you use the Link Handler in non-RTE context, e.g. to add a header_link, once you use pagination or the search you are redirected to the first tab and all link handler tabs disappear.

**Comment by maddy2101** [comment]
Hi, I had just the same problem, but resolved it by adding following snippet into linkhandler/Classes/Browser/RecordListRte.php
The problem is caused by the missing attributes stored in the $this->P array.
Does that help?

```php
/**
	 * Returns additional, local GET parameters to include in the links of the record list.
	 *
	 * @return string
	 */
	public function ext_addP() {

		$str = '';
		if (GeneralUtility::_GP('P')) {
			$str = '&' . http_build_query(array('P' => GeneralUtility::_GP('P')));
		}
		return $str . parent::ext_addP();
	}```

**Comment by astehlik** [comment]
Thanks a lot, Anja! This finally fixes it :)

**Comment by lorenzulrich** [comment]
Hi Alex. This issue related to a bug in Non-RTE context, e.g. the Link Browser of the "header_link" field in tt_content. This still doesn't work after updating to the latest version. Am I missing something?

**Comment by astehlik** [comment]
Hi Lorzenz,

this is really strange. I just tested it here (current TYPO3_6-2 branch with TYPO3 6.2.11) and it seems to work.

I placed some TSconfig in the page properties inside `mod.tx_linkhandler` and I get the tab only in that page tree and the tab does not disappear when I switch tabs or use the search.

Can you share some details?

Cheers,
Alex

**Comment by astehlik** [comment]
Hi Lorenz,

could you solve this issue? Or to you still have problems with tab switching / search?

Cheers,
Alex

**Comment by lorenzulrich** [comment]
You may close this again, it was a Git problem. Even though Git indicated that I was on the correct branch and the log matched the master of Linkhandler, the code obvisouly wasn't checked out. I deleted and clone the repo again and now everything works. Thanks.
