### ISSUE TITLE
Add generateLink Hook

### ISSUE THREAD

**Issue by dabjoern** [Intera/typo3-extension-linkhandler#4]
It would be great to introduce a new hook. We've got the problem that we have multiple detail pages for a certain record type. Right now it's not possible to let the linkhandler decide which is the "correct" detail page for the specific record. Since this is a very special requirement it's not useful to have the logic inside the linkhandler extension. But a hook will enable us to solve the described problem.

We'll provide the code ASAP.

**Comment by tritumRz** [comment]
Hi, here is the Code:
https://github.com/Intera/typo3-extension-linkhandler/pull/5

**Comment by astehlik** [comment]
Thanks for your contribution :)

Your pull request was merged.
