### ISSUE TITLE
Linkhander produces empty link with f:uri.page

### ISSUE THREAD

**Issue by Hoogendijk** [Intera/typo3-extension-linkhandler#6]
Linkhandler doesn't leave a lastTypoLinkUrl in the current contentObjectRenderer. This breaks UriBuilder::buildFrontendUri  in TYPO3 6.2.9.

suggested fix:
```patch
===================================================================
--- typo3conf/ext/linkhandler/Classes/LinkHandler.php	(revision 179114)
+++ typo3conf/ext/linkhandler/Classes/LinkHandler.php	(revision )
@@ -197,7 +197,9 @@
 
 		// Build the full link to the record
 		$this->localContentObjectRenderer->start($this->recordRow, '');
-		return $this->localContentObjectRenderer->typoLink($this->linkText, $this->typolinkConfiguration);
+		$link = $this->localContentObjectRenderer->typoLink($this->linkText, $this->typolinkConfiguration);
+		$this->contentObjectRenderer->lastTypoLinkUrl = $this->localContentObjectRenderer->lastTypoLinkUrl;
+		return $link;
 	}
```

**Comment by astehlik** [comment]
Thanks for the hint. Bugfix is commited :)

**Comment by astehlik** [comment]
Maybe this is also interesing for you:

https://github.com/Intera/typo3-extension-linkhandler#pass-on-parent-typolink-configuration

https://github.com/Intera/typo3-extension-linkhandler/commit/d0741d0918bdb1e1f78e81bf196aceb44bc06c5b

This allows the usage of (most) of the parameters passed to the UriBuilder.
