### ISSUE TITLE
Link in RTE causes that image is not displayed

### ISSUE THREAD

**Issue by bednee** [Intera/typo3-extension-linkhandler#7]
It's a weird bug. I have a text with images (one image) and if I put link to a record into the bodytext, image disappears from UI. Even HTML code is rendered as if there was no image at all (using css_styled_content).

Using TYPO3 6.2

**Comment by bednee** [comment]
Looks like it's caused by this line in LinkHandler.php:

$this->contentObjectRenderer->start($this->recordRow, '');

I have no idea how important this is, but in my test case commenting it out causes that image is displayed and link looks just fine.

**Comment by bednee** [comment]
See my comments in https://github.com/Intera/typo3-extension-linkhandler/issues/8

**Comment by astehlik** [comment]
Hi, thanks for your bug report.

Can you attach a link to the line where 

```
$this->contentObjectRenderer->start($this->recordRow, '');
```

is  called? I currently only see:

```
$this->localContentObjectRenderer->start($this->recordRow, '');
```

See also:
https://github.com/Intera/typo3-extension-linkhandler/blob/TYPO3_6-2/Classes/LinkHandler.php#L216

The ```localContentObjectRenderer``` should not influence the parent content object.

Cheers,
Alex

**Comment by bednee** [comment]
Hi,

that's odd. I downloaded the extension from GitHub a few months ago and 
it's just there. Looking at history of LinkHandler.php, I don't see it 
there. I have no idea.

Jan

Dne 2015-04-01 09:46, Alexander Stehlik napsal:

**Comment by astehlik** [comment]
Thats really odd.

Are you sure you are using the correct Git remote (https://github.com/Intera/typo3-extension-linkhandler.git) and branch (TYPO3_6-2) ;)

Maybe you can do a new ```git clone https://github.com/Intera/typo3-extension-linkhandler.git```?

**Comment by bednee** [comment]
I have just downloaded it as ZIP. Nevermind. I believe this can be 
closed.

Dne 2015-04-01 10:13, Alexander Stehlik napsal:
