### ISSUE TITLE
Title and Class not passed to Frontend

### ISSUE THREAD

**Issue by meincms** [Intera/typo3-extension-linkhandler#9]
I've tried to use a link class and a title in Frontend. Somehow it doesn't reach the Frontend, something goes wrong around this lines... but i didn't figure out what happens there.

https://github.com/Intera/typo3-extension-linkhandler/blob/TYPO3_6-2/Classes/LinkHandler.php#L217

		// Build the full link to the record
		$this->localContentObjectRenderer->start($this->recordRow, '');
		$this->localContentObjectRenderer->parameters = $this->contentObjectRenderer->parameters;
		$link = $this->localContentObjectRenderer->typoLink($this->linkText, $this->typolinkConfiguration);

$this->contentObjectRenderer->parameters... still contains the correct parameters...  but then in the end it gets lost in the frontend. any idea?

**Comment by astehlik** [comment]
Hi,

thank you for your report.

Can you explain what you mean by "use in the Frontend"? What exactly are you doing? Do you have a TypoScript snippet, a wizard link (e.g. header link) or a link in the RTE?

Kind regards,
Alex.

**Comment by meincms** [comment]
Hi Alex, Thanks for your fast reply. 

Well: 
- in the TYPO3 BE i choose a link, set a class i.E. in RTE. 
- I save the entry and check the output
- the link is rendered well to the right target-page of news ... but here i am missing the two additional attributes (class and title) which i just defined in the BE. 

i.E. if I define a normal link either to an internal page, external page etc... the title and also the class attribute are filled the way it should. 

any idea where this comes from?

**Comment by astehlik** [comment]
That is really strange. I did some tests in a clean TYPO3 6.2. installation with ```css_styled_content``` rendering and the Extensions ```linkhandler``` and ```news```.

This is what I did:

I added this to my Page TSconfig, so that I can choose ```external-link``` as a class for news links in the RTE.

```
RTE.classesAnchor.testlinkhandler {
	class = external-link
	type = tx_news_news
	titleText = A test class for news
}
```

When I create a news link that looks like this in the RTE HTML code:

```html
 <a href="record:tx_news_news:tx_news_domain_model_news:1" target="_blank" class="external-link" title="an external linkhandler link">
    testlink
</a> 
```

This is rendered in the Frontend:

```html
<a href="index.php?id=131&amp;tx_news_pi1%5Bnews%5D=1&amp;tx_news_pi1%5Bcontroller%5D=News&amp;tx_news_pi1%5Baction%5D=detail&amp;cHash=9a7f11e3ba8f0eaa378a4837a1fb3f2b" title="an external linkhandler link" target="_blank" class="external-link">
    testlink
</a>
```
As you can see, the title and the class are present.

Maybe the attributes are eaten by the ```lib.parseFunc_RTE``` settings in your TypoScript template?

**Comment by meincms** [comment]
Hi astehlik
Thanks for your fast reply. Sadly we still don't get the additional parameters... maybe this helps to find out more about what happens in my case:

print_r( $this->typolinkConfiguration); returns me following array: 

	Array
	(
		[parameter.] => Array
			(
				[stdWrap.] => Array
					(
						[cObject] => CASE
						[cObject.] => Array
							(
								[key.] => Array
									(
										[field] => pid
									)
	
								[74] => TEXT
								[74.] => Array
									(
										[value] => 89
									)
	
								[75] => TEXT
								[75.] => Array
									(
										[value] => 90
									)
	
								[87] => TEXT
								[87.] => Array
									(
										[value] => 129
									)
	
								[88] => TEXT
								[88.] => Array
									(
										[value] => 174
									)
	
								[218] => TEXT
								[218.] => Array
									(
										[value] => 219
									)
	
								[392] => TEXT
								[392.] => Array
									(
										[value] => 352
									)
	
								[351] => TEXT
								[351.] => Array
									(
										[value] => 357
									)
	
								[default] => TEXT
								[default.] => Array
									(
										[value] => 89
									)
	
							)
	
					)
	
			)
	
		[additionalParams] => &tx_news_pi1[news]={field:uid}&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail
		[additionalParams.] => Array
			(
				[insertData] => 1
			)
	
		[useCacheHash] => 1
		[parameter] =>  _blank button testtitle
	)



print_r($this->contentObjectRenderer->parameters); says: 

	Array
	(
		[record:news:tx_news_domain_model_news:1044] => 
		[_blank] => 
		[button] => 
		[testtitle] => 
		[allParams] => record:news:tx_news_domain_model_news:1044 _blank button testtitle
	)


i.E. if i do $this->typolinkConfiguration['parameter'] = '219 _blank button testtitle'; 
just before this line is rendered: 

	$link = $this->localContentObjectRenderer->typoLink($this->linkText, $this->typolinkConfiguration);

the link contains all of it's parameters.

**Comment by liayn** [comment]
your TS is wrong.
Your parameters.cObject overrides the parameters.

Try use parameters.prepend instead of cObject

**Comment by meincms** [comment]
Strange about it is, i do the configuration part in my extension. I didn't change the result in the extension... 


	// LINK-HANDLER CONFIGURATION

	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('
		mod.tx_linkhandler {
			news {
				label=News
				listTables=tx_news_domain_model_news
				pageTreeMountPoints {
					1 = 74
					2 = 75
					3 = 87
					4 = 88
					5 = 218
					6 = 351
					7 = 392
				}
			}
		}
		RTE.default.tx_linkhandler < mod.tx_linkhandler
		RTE.default.FE.tx_linkhandler < mod.tx_linkhandler
	');

**Comment by liayn** [comment]
Ok then this TS in generated by the extension and seems wrong.

**Comment by meincms** [comment]
I don't know, the case is built by the linkhandler or by typo3. it's created out of the pasted linkhandlerconfiguration above...

**Comment by meincms** [comment]
we've finally found it. 
There we go: it was not an issue of linkhandler, it was an issue of us... we used to handle it with that way:

  // LINKHANDLER

  tx_linkhandler {

	news {
		# force link generation also when the tt_news record are hidden or deleted
		forceLink = 0

		# typolink settings
		listTables = tx_news_domain_model_news

		# set pid for news detail pages
		typolink {
			#set news detail pid for different storage folders
			parameter.stdWrap.prepend = CASE
			parameter.stdWrap.prepend {
				key.field = pid
				74 = TEXT
				74.value = 89
				75 = TEXT
				75.value = 90
				default = TEXT
				default.value = 89
		}

		#set further additional parameter
		additionalParams = &tx_news_pi1[news]={field:uid}&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail
   	  	additionalParams.insertData = 1
		useCacheHash = 1
		}
	}
  }

}

**Comment by astehlik** [comment]
Thanks for your feedback.

Great that it is working now :)
